-- SkuMenu — menu contribution registry + layout map, root assembly, and central
-- sibling-list helpers. Workstream 2 (menu rework) of the Sku 42 rework.
--
-- PHASE A — additive plumbing that makes the ROOT menu assembly data-driven
-- WITHOUT changing the rendered tree. Today the top level is a hardcoded inline
-- sequence in SkuZOptions/Core.lua: one `InjectMenuItems(... ) + dynamic +
-- BuildChildren -> Module:MenuBuilder` block per module. Here that becomes:
--   * a REGISTRY of module "contributions" (id -> {label, build}) — WHAT a
--     module puts on the menu and how it builds its subtree, and
--   * a LAYOUT list (`rootLayout`) — WHERE/in-what-order those ids appear at the
--     root. Re-ordering the root is then a data edit to `rootLayout`, with no
--     code change and no hand-maintained sibling chain (the contribution/layout
--     decoupling that is the headline win of W2).
--
-- This sits ON TOP OF the existing rendering layer (SkuGenericMenuItem template +
-- SkuOptions:InjectMenuItems) — it is behaviour-preserving, not a renderer
-- replacement. The toggle/enum/range settings nodes are still generated by the
-- existing `SkuOptions:IterateOptionsArgs`; declarative archetype specs are a
-- later phase (M-B), shaped by the first real conversion rather than guessed now.
--
-- Lives on ns.Menu with a global SkuMenu alias (mirrors SkuUtil / SkuSettings).
--
-- Load position: TOC-loaded EARLY (right after SkuSettings.lua), before the
-- feature modules and before SkuZOptions/Core.lua. Only function definitions and
-- the registry population run at load; the renderer (InjectMenuItems) and the
-- module builders are resolved lazily, at menu-open time, when AssembleRoot runs.

local ADDON_NAME, ns = ...
ns = ns or {}

ns.Menu = ns.Menu or {}
SkuMenu = ns.Menu

-- registry[id] = { label = <string | function -> string>, build = function(entry),
--                  filterable = <bool?> }. `build` receives the dynamic root
-- entry as its argument and populates its children (same contract the old inline
-- BuildChildren closures had: build the subtree under the passed entry).
SkuMenu.registry = SkuMenu.registry or {}

-- Ordered list of registered ids shown at the root, top to bottom. THIS is the
-- layout — editing the order reorders the root menu with no code change. The
-- Accessibility ("Menue 7") grouping is still appended inline by
-- SkuZOptions/Core.lua after this list (a special hand-built grouping slated to
-- fold into the registry/layout in a later step).
SkuMenu.rootLayout = SkuMenu.rootLayout or {}

---------------------------------------------------------------------------------------------------------------------------------------
-- Register a module's root contribution.
function SkuMenu:RegisterModule(aId, aSpec)
	if type(aId) ~= "string" or type(aSpec) ~= "table" then
		if dprint then dprint("SkuMenu:RegisterModule: bad args", tostring(aId)) end
		return self
	end
	self.registry[aId] = aSpec
	return self
end

-- Set/replace the root layout order (a list of registered ids).
function SkuMenu:SetRootLayout(aIdList)
	self.rootLayout = aIdList or {}
	return self
end

---------------------------------------------------------------------------------------------------------------------------------------
-- Resolve a spec's label (string or function) at assembly time. Falls back to
-- the id so a mis-registered label never produces a nil menu name.
local function resolveLabel(aSpec, aId)
	local lbl = aSpec.label
	if type(lbl) == "function" then
		local ok, r = pcall(lbl)
		if ok and r ~= nil then return r end
		return aId
	end
	if lbl ~= nil then return lbl end
	return aId
end

-- Inject one registered module as a dynamic root entry whose BuildChildren runs
-- the registered builder. Mirrors EXACTLY the old hand-written per-module block
-- (entry.dynamic = true; BuildChildren -> Module:MenuBuilder(entry)). Returns the
-- created entry (or nil for an unregistered id).
function SkuMenu:InjectModuleEntry(aRootMenu, aId)
	local spec = self.registry[aId]
	if not spec then
		if dprint then dprint("SkuMenu:InjectModuleEntry: unregistered id", tostring(aId)) end
		return nil
	end
	local tEntry = SkuOptions:InjectMenuItems(aRootMenu, {resolveLabel(spec, aId)}, SkuGenericMenuItem)
	tEntry.dynamic = true
	if spec.filterable then
		tEntry.filterable = true
	end
	local buildFn = spec.build
	tEntry.BuildChildren = function(self)
		if buildFn then
			buildFn(self)
		end
	end
	return tEntry
end

-- Assemble the registered root entries, in layout order, into aRootMenu.
-- Injecting one at a time into the same parent reproduces the original prev/next
-- sibling chain exactly (InjectMenuItems links each new item to the previous).
function SkuMenu:AssembleRoot(aRootMenu)
	for i = 1, #self.rootLayout do
		self:InjectModuleEntry(aRootMenu, self.rootLayout[i])
	end
	return self
end

---------------------------------------------------------------------------------------------------------------------------------------
-- Central sibling-list helpers. Insertion already routes through InjectMenuItems
-- (which wires prev/next centrally); REMOVAL is the asymmetric gap today — ad-hoc
-- sites re-derive position by index and can leave the prev/next chain broken.
-- These give one splice point for both, for the M-D phase to route removals
-- through (not yet wired into existing callers — additive for now).

-- Append items under a parent via the existing renderer. Returns the last entry.
function SkuMenu:Insert(aParent, aNames, aTemplate)
	return SkuOptions:InjectMenuItems(aParent, aNames, aTemplate or SkuGenericMenuItem)
end

-- Remove an entry from its parent's children, fixing the prev/next sibling chain.
-- Handles both parent shapes the renderer uses: a node (list in parent.children)
-- and the root array (the parent IS the list). Returns the removed entry.
function SkuMenu:Remove(aEntry)
	if not aEntry or not aEntry.parent then
		return aEntry
	end
	local siblings = aEntry.parent.children or aEntry.parent
	local idx
	for x = 1, #siblings do
		if siblings[x] == aEntry then
			idx = x
			break
		end
	end
	if not idx then
		return aEntry
	end
	local prev, nxt = aEntry.prev, aEntry.next
	if prev then prev.next = nxt end
	if nxt then nxt.prev = prev end
	table.remove(siblings, idx)
	aEntry.prev, aEntry.next = nil, nil
	return aEntry
end

---------------------------------------------------------------------------------------------------------------------------------------
-- Root contributions. Centralised here for this first construct (lowest risk,
-- one reviewable file); moving each RegisterModule call into its owning module is
-- a trivial follow-up — the mechanism is identical, since builders resolve their
-- module globals lazily at open time. Labels resolve at open time too, matching
-- the original (which read L[...] inside the open handler).
local function L() return Sku.L end

SkuMenu:RegisterModule("SkuNav",   { label = function() return L()["SkuNavMenuEntry"]   end, build = function(entry) SkuNav:MenuBuilder(entry)   end })
SkuMenu:RegisterModule("SkuMob",   { label = function() return L()["SkuMobMenuEntry"]   end, build = function(entry) SkuMob:MenuBuilder(entry)   end })
SkuMenu:RegisterModule("SkuChat",  { label = function() return L()["SkuChatMenuEntry"]  end, build = function(entry) SkuChat:MenuBuilder(entry)  end })
SkuMenu:RegisterModule("SkuQuest", { label = function() return L()["SkuQuestMenuEntry"] end, build = function(entry) SkuQuest:MenuBuilder(entry) end })
SkuMenu:RegisterModule("SkuCore",  { label = function() return L()["SkuCoreMenuEntry"]  end, build = function(entry) SkuCore:MenuBuilder(entry)  end })
SkuMenu:RegisterModule("SkuAuras", { label = function() return L()["SkuAurasMenuEntry"] end, build = function(entry) SkuAuras:MenuBuilder(entry) end })

-- Game Options: Blizzard's built-in game options (modern Settings system, else
-- only reachable via the Escape menu) made accessible through Sku's menu. Logic
-- in SkuCore/gameOptions.lua. Title is locale-computed at open time, as before.
SkuMenu:RegisterModule("GameOptions", {
	label = function() return (GetLocale and GetLocale() == "deDE") and "Spieloptionen" or "Game Options" end,
	build = function(entry)
		if SkuCore and SkuCore.GameOptionsMenuBuilder then
			SkuCore:GameOptionsMenuBuilder(entry)
		end
	end,
})

-- Default root layout — IDENTICAL order to the old hardcoded sequence.
SkuMenu:SetRootLayout({
	"SkuNav",
	"SkuMob",
	"SkuChat",
	"SkuQuest",
	"SkuCore",
	"SkuAuras",
	"GameOptions",
})
