#!/usr/bin/env python3
# Build Sku/locales/frFR.lua from the enUS table plus translation part-files.
#
# WORKFLOW
#   py -3 _frfr_locale.py extract          -> scratch/frfr_src.tsv  (idx, key, enUS)
#   py -3 _frfr_locale.py batch <n> <size> -> print one batch to translate
#   ... write scratch/parts/frfr_<n>.tsv as  idx <TAB> french
#   py -3 _frfr_locale.py assemble         -> Sku/locales/frFR.lua + validation
#
# SAFETY: assemble falls back to the enUS value for any entry not yet
# translated, so the generated file is ALWAYS complete and valid Lua. A
# partially translated frFR.lua behaves exactly like today's English fallback
# for the untranslated remainder - never blank, never missing keys.
#
# The keys of Sku's locale table are a MIX of German and English originals
# (~2000 German-keyed, ~1200 English-keyed), so the enUS *value* is the only
# field that is uniformly English. That is the translation source.

import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
LOCALES = os.path.join(REPO, "Sku", "locales")
SCRATCH = os.path.join(HERE, "_frfr_scratch")
PARTS = os.path.join(SCRATCH, "parts")
SRC = os.path.join(SCRATCH, "frfr_src.tsv")

RX = re.compile(r'^\s*L\[(".*?(?<!\\)")\]\s*=\s*(".*?(?<!\\)")\s*(--.*)?$')


def decode(lit):
    body = lit[1:-1]
    out, i = [], 0
    while i < len(body):
        if body[i] == "\\" and i + 1 < len(body):
            out.append({"n": "\n", "t": "\t"}.get(body[i + 1], body[i + 1]))
            i += 2
        else:
            out.append(body[i])
            i += 1
    return "".join(out)


def encode(s):
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\t", "\\t")


def parse(path):
    """Ordered [(key, value)] from a locale file."""
    rows = []
    with io.open(path, encoding="utf-8-sig") as fh:
        for line in fh:
            if not line.lstrip().startswith("L["):
                continue
            m = RX.match(line.rstrip())
            if m:
                rows.append((decode(m.group(1)), decode(m.group(2))))
    return rows


def esc_line(s):
    """One-line, round-trippable form for TSV batch/part files."""
    return (s.replace("\\", "\\\\").replace("\r", "\\r")
             .replace("\n", "\\n").replace("\t", "\\t"))


def unesc_line(s):
    out, i = [], 0
    while i < len(s):
        if s[i] == "\\" and i + 1 < len(s):
            out.append({"n": "\n", "r": "\r", "t": "\t", "\\": "\\"}.get(s[i + 1], s[i + 1]))
            i += 2
        else:
            out.append(s[i])
            i += 1
    return "".join(out)


def restore_edges(src, dst):
    """Give dst the same leading/trailing spaces as src."""
    lead = src[:len(src) - len(src.lstrip(" "))]
    trail = src[len(src.rstrip(" ")):] if src.strip(" ") else ""
    return lead + dst.strip(" ") + trail


def load_parts():
    """idx -> french, from every part file written so far."""
    out = {}
    if not os.path.isdir(PARTS):
        return out
    for name in sorted(os.listdir(PARTS)):
        if not name.endswith(".tsv"):
            continue
        with io.open(os.path.join(PARTS, name), encoding="utf-8") as fh:
            for line in fh:
                line = line.rstrip("\n").rstrip("\r")
                if not line or "\t" not in line:
                    continue
                idx, fr = line.split("\t", 1)
                try:
                    out[int(idx)] = unesc_line(fr)
                except ValueError:
                    pass
    return out


def cmd_extract():
    os.makedirs(PARTS, exist_ok=True)
    rows = parse(os.path.join(LOCALES, "enUS.lua"))
    with io.open(SRC, "w", encoding="utf-8", newline="\n") as fh:
        for i, (k, v) in enumerate(rows):
            fh.write("%d\t%s\t%s\n" % (i, k.replace("\t", " "), v.replace("\t", " ")))
    print("extracted %d entries -> %s" % (len(rows), SRC))


def cmd_batch(n, size):
    rows = parse(os.path.join(LOCALES, "enUS.lua"))
    done = load_parts()
    start, end = n * size, min((n + 1) * size, len(rows))
    shown = 0
    for i in range(start, end):
        if i in done:
            continue
        k, v = rows[i]
        print("%d\t%s" % (i, esc_line(v)))
        shown += 1
    print("--- batch %d: %d untranslated of %d..%d (total %d) ---"
          % (n, shown, start, end - 1, len(rows)))


def cmd_assemble():
    rows = parse(os.path.join(LOCALES, "enUS.lua"))
    fr = load_parts()
    out = [
        "--[[",
        "\tSku French locale.",
        "",
        "\tGENERATED by dev/rework-docs/_frfr_locale.py - re-run assemble after",
        "\tediting the translation part files; do not hand-edit this file.",
        "",
        "\tMachine translated from the enUS values. The keys of this table are a",
        "\tmix of German and English originals, so the enUS value is the only",
        "\tuniformly English field and therefore the translation source.",
        "",
        "\tEntries not yet translated fall back to their English value, which is",
        "\texactly what a French client saw before this file existed.",
        "",
        "\tInstructions for translators:",
        "\t\t- don't omit leading or trailing spaces",
        "\t\t- don't omit semicolons",
        "\t\t- don't replace semicolons by spaces",
        "]]",
        "",
        'local L = LibStub("AceLocale-3.0"):NewLocale("Sku", "frFR")',
        "if not L then return end",
    ]
    translated = 0
    for i, (k, v) in enumerate(rows):
        val = fr.get(i)
        if val is None or val == "":
            val = v
        else:
            # Leading/trailing spaces are load-bearing in this table (the file
            # header warns translators about exactly that) but they do not
            # survive a TSV round-trip and are invisible in review. So they are
            # not carried in the translation at all: re-apply the English
            # entry's own edge whitespace to the French text.
            val = restore_edges(v, val)
            translated += 1
        out.append('L["%s"] = "%s"' % (encode(k), encode(val)))
    out.append('L["locale"] = "frFR"')
    out.append("")
    dest = os.path.join(LOCALES, "frFR.lua")
    with io.open(dest, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\ufeff" + "\n".join(out))

    # ---- validation against the enUS source -------------------------------
    problems = []
    for i, (k, v) in enumerate(rows):
        val = fr.get(i)
        if val is None or val == "":
            continue
        val = restore_edges(v, val)   # validate what actually gets written
        if val.count("%s") != v.count("%s") or val.count("%d") != v.count("%d"):
            problems.append("%d placeholder mismatch: %r -> %r" % (i, v, val))
        if v[:1] == " " and val[:1] != " ":
            problems.append("%d lost leading space: %r -> %r" % (i, v, val))
        if v[-1:] == " " and val[-1:] != " ":
            problems.append("%d lost trailing space: %r -> %r" % (i, v, val))
        if v.count(";") != val.count(";"):
            problems.append("%d semicolon count: %r -> %r" % (i, v, val))
    print("wrote %s" % dest)
    print("entries %d, translated %d (%.1f%%), english fallback %d"
          % (len(rows), translated, translated / len(rows) * 100, len(rows) - translated))
    if problems:
        print("\nVALIDATION PROBLEMS (%d):" % len(problems))
        for p in problems[:40]:
            print("  " + p)
    else:
        print("validation clean")


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "assemble"
    if cmd == "extract":
        cmd_extract()
    elif cmd == "batch":
        cmd_batch(int(sys.argv[2]), int(sys.argv[3]) if len(sys.argv) > 3 else 200)
    else:
        cmd_assemble()
