"""Generate Sku/SkuDB/assets/instances.lua from Questie's dungeons table.

Source: <Questie>/Database/Zones/data/dungeons.lua - instance areaId ->
{name, alternativeAreaIds, parentZone, entrance coordinates}. We keep only
what the entrance fallback needs: for EVERY area id (main + alternates) a
list of entrances {parentAreaId, x, y[, faction]}. Faction-specific
battleground entrances carry "Alliance"/"Horde" as 4th element (Questie
writes them as `(isHorde and {..}) or {..}` ternaries).

The base table is the pre-WotLK state, which is what the TBC Anniversary
client wants; Questie's `Expansions.Current >= Wotlk` overrides (Stockade,
Deeprun Tram, Naxxramas) are emitted behind a GetBuildInfo() gate so the
file keeps working when the anniversary cycle reaches WotLK.

Run: py -3 dev/rework-docs/_gen_instance_entrances.py
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
SRC = (r"C:\Program Files (x86)\World of Warcraft\_anniversary_"
       r"\Interface\AddOns\Questie\Database\Zones\data\dungeons.lua")
OUT = os.path.join(ROOT, "Sku", "SkuDB", "assets", "instances.lua")

text = open(SRC, encoding="utf-8", errors="replace").read()

TERN = re.compile(r"\(isHorde and \{([\d., ]+)\}\) or \{([\d., ]+)\}")
PLAIN = re.compile(r"\{(\d+), ?([\d.]+), ?([\d.]+)\}")
ROW = re.compile(r'^\s+\[(\d+)\] = \{"([^"]+)",(\{[\d,]*\}|nil),(\d+),\{(.*)\}\},')


def parse_locs(s):
    """Return list of (parent, x, y, faction-or-None)."""
    out = []
    rest = s
    for m in TERN.finditer(s):
        h = [t.strip() for t in m.group(1).split(",")]
        a = [t.strip() for t in m.group(2).split(",")]
        out.append((int(h[0]), h[1], h[2], "Horde"))
        out.append((int(a[0]), a[1], a[2], "Alliance"))
        rest = rest.replace(m.group(0), "")
    for m in PLAIN.finditer(rest):
        out.append((int(m.group(1)), m.group(2), m.group(3), None))
    return out


# base table region: from "local dungeons = {" to the closing "}" line
i = text.index("local dungeons = {")
j = text.index("\n}", i)
base = text[i:j]

entries = {}   # main id -> (name, [alt ids], [locs])
for line in base.splitlines():
    m = ROW.match(line)
    if not m:
        continue
    mid = int(m.group(1))
    name = m.group(2)
    alts = [int(x) for x in re.findall(r"\d+", m.group(3))] if m.group(3) != "nil" else []
    locs = parse_locs(m.group(5))
    if locs:
        entries[mid] = (name, alts, locs)

# WotLK override block (applies when the anniversary cycles to a 3.x client)
wi = text.index("Expansions.Current >= Expansions.Wotlk")
wj = text.index("\nend", wi)
wotlk = []
for line in text[wi:wj].splitlines():
    m = re.match(r"\s+dungeons\[(\d+)\]\[4\] = \{(.*)\}( --.*)?$", line)
    if m:
        wotlk.append((int(m.group(1)), parse_locs(m.group(2)), (m.group(3) or "").strip()))

def lua_locs(locs):
    parts = []
    for p, x, y, fac in locs:
        if fac:
            parts.append('{%d,%s,%s,"%s"}' % (p, x, y, fac))
        else:
            parts.append("{%d,%s,%s}" % (p, x, y))
    return "{" + ",".join(parts) + "}"


lines = []
lines.append("-- GENERATED by dev/rework-docs/_gen_instance_entrances.py from Questie's")
lines.append("-- Database/Zones/data/dungeons.lua - do not edit records by hand, re-run")
lines.append("-- the generator instead. Instance/battleground areaId -> entrance list")
lines.append("-- {parentAreaId, x, y[, \"Alliance\"|\"Horde\"]}. Used by the quest-menu")
lines.append("-- entrance fallback for spawns inside instances (no world map -> route")
lines.append("-- to the entrance instead of showing nothing).")
lines.append("SkuDB.InstanceEntrances = {")
for mid in sorted(entries):
    name, alts, locs = entries[mid]
    lines.append("\t[%d] = %s, -- %s" % (mid, lua_locs(locs), name))
lines.append("}")
lines.append("")
lines.append("-- alternative area ids (wings/sub-areas) share their dungeon's entrances")
for mid in sorted(entries):
    name, alts, locs = entries[mid]
    for a in alts:
        lines.append("SkuDB.InstanceEntrances[%d] = SkuDB.InstanceEntrances[%d] -- %s" % (a, mid, name))
lines.append("")
lines.append("-- WotLK-era entrance moves - active once the anniversary cycle reaches a 3.x client")
lines.append('if string.byte(GetBuildInfo(), 1) >= 51 then')
for mid, locs, comment in wotlk:
    lines.append("\tSkuDB.InstanceEntrances[%d] = %s %s" % (mid, lua_locs(locs), comment))
lines.append("end")

with open(OUT, "w", encoding="utf-8", newline="\r\n") as fh:
    fh.write("\n".join(lines) + "\n")
print("entries: %d main, %d alt aliases, %d wotlk overrides"
      % (len(entries), sum(len(a) for _, a, _ in entries.values()), len(wotlk)))
print("wrote", OUT)
