#!/usr/bin/env python3
# Generate Sku's frFR game-name chunk files from Questie's shipped frFR lookups.
#
# WHY THIS EXISTS
# Sku's deDE/enUS name tables were originally imported from Questie: the
# NpcData.Keys schema is Questie's npc schema field for field, the ids match
# exactly, and even the storage form (loadstring([[return { ... }]])) is the
# same. Questie also ships frFR lookups for npcs/objects/items/quests across
# Classic/TBC/Wotlk, so French game names come from Blizzard's own strings -
# they are IMPORTED, never machine translated. That is what keeps route names
# searchable for a French player.
#
# SHAPES
#   npcs    Questie [id] = {"Name", "SubName"}     -> Sku identical
#   objects Questie [id] = "Name"                  -> Sku identical
#   items   Questie [id] = "Name"                  -> Sku identical
#   quests  Questie [id] = {"Title", {objectives}} -> Sku {"Title", nil, {objectives}}
#           (Sku carries an extra unused slot in position 2)
#
# Only ids Sku actually knows are emitted, so the French set can never be
# larger than the German one it mirrors.
#
# Usage:  py -3 dev/rework-docs/_gen_frfr_names.py [--dry-run]

import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SKU = os.path.join(REPO, "Sku", "SkuDB", "assets")
QUESTIE = r"C:\Program Files (x86)\World of Warcraft\_anniversary_\Interface\AddOns\Questie\Localization\lookups"

CHUNK_LINES = 500          # match the existing files' chunk granularity
ID_RX = re.compile(r"^\s*\[(\d+)\]\s*=\s*(.*?),?\s*$")


def read_questie(path):
    """id -> raw lua value text, for one Questie lookup file."""
    out = {}
    if not os.path.exists(path):
        return out
    with open(path, encoding="utf-8", errors="replace") as fh:
        for line in fh:
            m = ID_RX.match(line)
            if m:
                out[int(m.group(1))] = m.group(2).rstrip().rstrip(",")
    return out


def read_sku_ids(path, table):
    """The id set Sku already has for a given chunk table path."""
    ids = set()
    if not os.path.exists(path):
        return ids
    inchunk = False
    with open(path, encoding="utf-8", errors="replace") as fh:
        for line in fh:
            if "SkuDBChunks[#SkuDBChunks+1]" in line:
                inchunk = ('"%s"' % table) in line
                if inchunk and "[=[return {" in line:
                    m = ID_RX.match(line.split("[=[return {", 1)[-1])
                    if m:
                        ids.add(int(m.group(1)))
                continue
            if inchunk:
                m = ID_RX.match(line)
                if m:
                    ids.add(int(m.group(1)))
    return ids


def skip_lua_string(s, i):
    """Given s[i] == '"', return index just past the closing quote."""
    i += 1
    while i < len(s):
        if s[i] == "\\":
            i += 2
            continue
        if s[i] == '"':
            return i + 1
        i += 1
    return i


def quest_to_sku(value):
    """{"Title", {objs}}  ->  {"Title",nil,{objs}}   (insert Sku's unused slot)"""
    v = value.strip()
    if not v.startswith("{"):
        return None
    i = 1
    while i < len(v) and v[i].isspace():
        i += 1
    if i >= len(v) or v[i] != '"':
        return None
    end = skip_lua_string(v, i)
    title = v[i:end]
    rest = v[end:].lstrip()
    if rest.startswith(","):
        rest = rest[1:].lstrip()
    if rest.endswith("}"):
        rest = rest[:-1].rstrip().rstrip(",")
    if rest == "":
        rest = "nil"
    return "{%s,nil,%s}" % (title, rest)


def emit(path, decls, tables, header):
    """Write one Sku chunk file. `tables` is [(lua_path, {id: value_text})]."""
    lines = [
        "-- GENERATED by dev/rework-docs/_gen_frfr_names.py - do not hand-edit.",
        "-- French game names imported from Questie's shipped frFR lookups",
        "-- (Blizzard's own strings, so they match what a frFR client displays).",
        "-- " + header,
        "",
    ]
    lines.extend(decls)
    lines.append("SkuDBChunks = SkuDBChunks or {}")
    lines.append("")
    total = 0
    for lua_path, rows in tables:
        ids = sorted(rows)
        total += len(ids)
        for start in range(0, len(ids), CHUNK_LINES):
            batch = ids[start:start + CHUNK_LINES]
            lines.append(
                'SkuDBChunks[#SkuDBChunks+1] = {"%s", [=[return {' % lua_path)
            for i in batch:
                lines.append("[%d] = %s," % (i, rows[i]))
            lines.append("}]=]}")
    lines.append("")
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines))
    return total


def main():
    dry = "--dry-run" in sys.argv
    os.makedirs(os.path.join(SKU, "frFR"), exist_ok=True)
    os.makedirs(os.path.join(SKU, "WotLK", "frFR"), exist_ok=True)

    # Questie families, unioned oldest -> newest so later expansions win.
    def q(fam, *packs):
        merged = {}
        for p in packs:
            merged.update(read_questie(os.path.join(QUESTIE, p, fam, "frFR.lua")))
        return merged

    base_packs = ("Classic", "TBC")
    wotlk_packs = ("Classic", "TBC", "Wotlk")

    specs = [
        # (out file, sku source file, sku table, questie family, packs, lua path, decl)
        ("frFR/creatures_frFR.lua", "creatures.lua", "SkuDB.NpcData.Names.deDE",
         "lookupNpcs", base_packs, "SkuDB.NpcData.Names.frFR",
         ['SkuDB.NpcData.Names["frFR"] = SkuDB.NpcData.Names["frFR"] or {}']),
        ("frFR/objects_frFR.lua", "objects.lua", "SkuDB.objectLookup.deDE",
         "lookupObjects", base_packs, "SkuDB.objectLookup.frFR",
         ['SkuDB.objectLookup["frFR"] = SkuDB.objectLookup["frFR"] or {}']),
        ("frFR/items_frFR.lua", "items.lua", "SkuDB.itemLookup.deDE",
         "lookupItems", base_packs, "SkuDB.itemLookup.frFR",
         ['SkuDB.itemLookup["frFR"] = SkuDB.itemLookup["frFR"] or {}']),
        ("frFR/quests_frFR.lua", "quests.lua", "SkuDB.questLookup.deDE",
         "lookupQuests", base_packs, "SkuDB.questLookup.frFR",
         ['SkuDB.questLookup["frFR"] = SkuDB.questLookup["frFR"] or {}']),

        ("WotLK/frFR/creatures_frFR.lua", "WotLK/creatures.lua",
         "SkuDB.WotLK.NpcData.Names.deDE", "lookupNpcs", wotlk_packs,
         "SkuDB.WotLK.NpcData.Names.frFR",
         ['SkuDB.WotLK.NpcData.Names["frFR"] = SkuDB.WotLK.NpcData.Names["frFR"] or {}']),
        ("WotLK/frFR/objects_frFR.lua", "WotLK/objects.lua",
         "SkuDB.WotLK.objectLookup.deDE", "lookupObjects", wotlk_packs,
         "SkuDB.WotLK.objectLookup.frFR",
         ['SkuDB.WotLK.objectLookup["frFR"] = SkuDB.WotLK.objectLookup["frFR"] or {}']),
        ("WotLK/frFR/items_frFR.lua", "WotLK/items.lua",
         "SkuDB.WotLK.itemLookup.deDE", "lookupItems", wotlk_packs,
         "SkuDB.WotLK.itemLookup.frFR",
         ['SkuDB.WotLK.itemLookup["frFR"] = SkuDB.WotLK.itemLookup["frFR"] or {}']),
        ("WotLK/frFR/quests_frFR.lua", "WotLK/quests.lua",
         "SkuDB.WotLK.questLookup.deDE", "lookupQuests", wotlk_packs,
         "SkuDB.WotLK.questLookup.frFR",
         ['SkuDB.WotLK.questLookup["frFR"] = SkuDB.WotLK.questLookup["frFR"] or {}']),
    ]

    grand = 0
    for out, src, table, fam, packs, lua_path, decls in specs:
        sku_ids = read_sku_ids(os.path.join(SKU, src.replace("/", os.sep)), table)
        qrows = q(fam, *packs)
        rows = {}
        dropped = 0
        for i in sorted(sku_ids):
            v = qrows.get(i)
            if v is None:
                continue
            if fam == "lookupQuests":
                v = quest_to_sku(v)
                if v is None:
                    dropped += 1
                    continue
            rows[i] = v
        cov = (len(rows) / len(sku_ids) * 100) if sku_ids else 0.0
        print("%-34s sku=%6d  fr=%6d  (%5.1f%%)%s"
              % (out, len(sku_ids), len(rows), cov,
                 "  unparsed=%d" % dropped if dropped else ""))
        if not dry:
            grand += emit(os.path.join(SKU, out.replace("/", os.sep)),
                          decls, [(lua_path, rows)], "%s from Questie %s"
                          % (lua_path, "+".join(packs)))
    if not dry:
        print("\ntotal frFR rows written: %d" % grand)


if __name__ == "__main__":
    main()
