#!/usr/bin/env python3
# Read the /skudebug dumpmapnames and dumpspells captures out of Sku's
# SavedVariables and report what they contain.
#
# Parsing follows the project rule: locate the block, capture it by brace-depth
# counting, then read entries with plain string ops - no regex over the body.
#
# Usage: py -3 dev/rework-docs/_read_frfr_dumps.py [--write]
#        --write also emits the shipped frFR tables.

import io
import os
import sys

SV = (r"C:\Program Files (x86)\World of Warcraft\_anniversary_"
      r"\WTF\Account\1107979492#1\SavedVariables\Sku.lua")
REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUTDIR = os.path.join(REPO, "Sku", "SkuDB", "assets", "frFR")


def find_block(lines, key, start=0):
    """Return (startIdx, endIdx) of the ["key"] = { ... } block."""
    needle = '["%s"] = {' % key
    for i in range(start, len(lines)):
        if lines[i].strip().startswith(needle):
            depth = 0
            for j in range(i, len(lines)):
                depth += lines[j].count("{") - lines[j].count("}")
                if depth <= 0:
                    return i, j
    return None, None


def read_pairs(lines, lo, hi):
    """[<id>] = "value", entries inside the given line range."""
    out = {}
    for k in range(lo, hi + 1):
        s = lines[k].strip()
        if not s.startswith("["):
            continue
        close = s.find("]")
        if close < 0:
            continue
        key = s[1:close].strip()
        rest = s[close + 1:].lstrip()
        if not rest.startswith("="):
            continue
        val = rest[1:].strip().rstrip(",").strip()
        if len(val) >= 2 and val[0] == '"' and val[-1] == '"':
            try:
                out[int(key)] = val[1:-1]
            except ValueError:
                pass
    return out


def scalar(lines, lo, hi, key):
    needle = '["%s"] =' % key
    for k in range(lo, hi + 1):
        s = lines[k].strip()
        if s.startswith(needle):
            v = s[len(needle):].strip().rstrip(",").strip()
            return v.strip('"')
    return None


def main():
    lines = io.open(SV, encoding="utf-8", errors="replace").read().splitlines()

    mlo, mhi = find_block(lines, "mapNameDump")
    slo, shi = find_block(lines, "spellNameDump")
    if mlo is None or slo is None:
        print("dump block(s) missing - run /skudebug dumpmapnames and dumpspells, then /reload")
        return

    mloc = scalar(lines, mlo, mhi, "locale")
    alo, ahi = find_block(lines, "areas", mlo)
    plo, phi = find_block(lines, "maps", mlo)
    areas = read_pairs(lines, alo, ahi) if alo else {}
    maps = read_pairs(lines, plo, phi) if plo else {}

    sloc = scalar(lines, slo, shi, "locale")
    nlo, nhi = find_block(lines, "names", slo)
    spells = read_pairs(lines, nlo, nhi) if nlo else {}

    print("mapNameDump   locale=%s  areas=%d  maps=%d" % (mloc, len(areas), len(maps)))
    print("spellNameDump locale=%s  spells=%d" % (sloc, len(spells)))
    for label, d in (("area", areas), ("map", maps), ("spell", spells)):
        sample = sorted(d.items())[:3]
        print("   %-6s sample: %s" % (label, sample))

    if mloc != "frFR" or sloc != "frFR":
        print("\nWARNING: expected frFR. Dump was taken on the wrong client - do not ship this.")
        return
    if "--write" not in sys.argv:
        print("\n(dry run - pass --write to emit the frFR tables)")
        return

    os.makedirs(OUTDIR, exist_ok=True)

    def emit(path, header, decls, body_lines):
        with io.open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write("-- GENERATED by dev/rework-docs/_read_frfr_dumps.py - do not hand-edit.\n")
            fh.write("-- %s\n--\n" % header)
            fh.write("-- Captured from a real frFR client via /skudebug, so these are the\n")
            fh.write("-- client's OWN localized strings - imported, never machine translated.\n\n")
            fh.write(decls + "\n")
            fh.write("\n".join(body_lines) + "\n")

    # zone / map names -> a plain table the runtime fill prefers over C_Map
    body = ['SkuDB.frFRAreaNames = {']
    for i, v in sorted(areas.items()):
        body.append('[%d] = "%s",' % (i, v.replace('\\', '\\\\').replace('"', '\\"')))
    body.append('}')
    body.append('SkuDB.frFRMapNames = {')
    for i, v in sorted(maps.items()):
        body.append('[%d] = "%s",' % (i, v.replace('\\', '\\\\').replace('"', '\\"')))
    body.append('}')
    emit(os.path.join(OUTDIR, "mapnames_frFR.lua"),
         "French zone and map names (areaId -> name, uiMapId -> name)",
         "SkuDB = SkuDB or {}", body)

    # spell names -> chunked, same shape as the other generated frFR files
    # Path must (a) map to a family in SkuDBFamilyOfPath and (b) END in the
    # locale so SkuDBLocaleOfPath gates it - otherwise every client builds it.
    sbody = ['SkuDB.spellNames = SkuDB.spellNames or {}',
             'SkuDB.spellNames["frFR"] = SkuDB.spellNames["frFR"] or {}',
             'SkuDBChunks = SkuDBChunks or {}', '']
    ids = sorted(spells)
    for start in range(0, len(ids), 500):
        sbody.append('SkuDBChunks[#SkuDBChunks+1] = {"SkuDB.spellNames.frFR", [=[return {')
        for i in ids[start:start + 500]:
            sbody.append('[%d] = "%s",' % (i, spells[i].replace('\\', '\\\\').replace('"', '\\"')))
        sbody.append('}]=]}')
    emit(os.path.join(OUTDIR, "spellnames_frFR.lua"),
         "French spell names (spellId -> name) from GetSpellInfo on a frFR client",
         "SkuDB = SkuDB or {}", sbody)

    print("\nwrote %s" % OUTDIR)


if __name__ == "__main__":
    main()
