#import <Cocoa/Cocoa.h>

@interface SkuDelegate:NSObject<NSApplicationDelegate,NSWindowDelegate>
@property NSWindow *window; @property NSTextField *status,*path,*output; @property NSPopUpButton *games,*languages;
@property NSButton *login,*questie,*atlas,*details,*pawn,*dbm,*gtfo,*bugsack,*update,*repair,*inventory,*cancel; @property NSProgressIndicator *progress;
@property NSMutableArray<NSString*> *paths; @property NSUserDefaults *prefs; @property NSTask *task; @property NSPipe *pipe;
@property NSDictionary *latestCurated;
@end

@implementation SkuDelegate
- (NSTextField*)label:(NSString*)s size:(CGFloat)n bold:(BOOL)b { NSTextField*v=[NSTextField wrappingLabelWithString:s]; v.font=b?[NSFont boldSystemFontOfSize:n]:[NSFont systemFontOfSize:n]; v.accessibilityLabel=s; return v; }
- (NSButton*)button:(NSString*)s action:(SEL)a { NSButton*b=[NSButton buttonWithTitle:s target:self action:a]; b.accessibilityLabel=s; return b; }
- (void)applicationDidFinishLaunching:(NSNotification*)n { [NSApp setActivationPolicy:NSApplicationActivationPolicyRegular]; self.prefs=[[NSUserDefaults alloc]initWithSuiteName:@"org.sku-project.installer"]; self.paths=[NSMutableArray array]; [self buildWindow]; [self loadConfiguration]; [self.window makeKeyAndOrderFront:nil]; [NSApp activateIgnoringOtherApps:YES]; [self refreshStatus:YES]; [self checkInstallerAutomatically]; }
- (void)buildWindow {
 self.window=[[NSWindow alloc]initWithContentRect:NSMakeRect(0,0,780,880) styleMask:NSWindowStyleMaskTitled|NSWindowStyleMaskClosable|NSWindowStyleMaskMiniaturizable|NSWindowStyleMaskResizable backing:NSBackingStoreBuffered defer:NO]; self.window.title=@"Sku Installer und Updater"; self.window.delegate=self; self.window.minSize=NSMakeSize(720,800); [self.window center];
 NSTextField*heading=[self label:@"Sku Installer und Updater" size:24 bold:YES]; heading.accessibilityRoleDescription=@"Überschrift";
 self.status=[self label:@"Der Status wird geprüft." size:15 bold:NO]; self.status.accessibilityRoleDescription=@"Status";
 self.games=[NSPopUpButton new]; self.games.accessibilityLabel=@"Installierte WoW-Version"; self.games.target=self; self.games.action=@selector(gameChanged:);
 self.path=[self label:@"Noch kein AddOns-Ordner ausgewählt." size:11 bold:NO]; self.path.textColor=NSColor.secondaryLabelColor;
 self.languages=[NSPopUpButton new]; [self.languages addItemsWithTitles:@[@"Deutsch",@"Deutsch schnell",@"Englisch"]]; self.languages.accessibilityLabel=@"Sprachpaket"; self.languages.target=self; self.languages.action=@selector(changed:);
 self.login=[NSButton checkboxWithTitle:@"WoW Login Tool für Hammerspoon installieren und aktualisieren" target:self action:@selector(changed:)];
 self.questie=[NSButton checkboxWithTitle:@"Questie verwalten – verfügbar 11.37.1" target:self action:@selector(changed:)]; self.questie.accessibilityHelp=@"Installiert und aktualisiert die Anniversary-Version von Questie über CurseForge.";
 self.atlas=[NSButton checkboxWithTitle:@"AtlasLootClassic Anniversary verwalten – verfügbar 2.5.6.12334" target:self action:@selector(changed:)]; self.atlas.accessibilityHelp=@"Installiert und aktualisiert die besondere Anniversary-Version von AtlasLootClassic über CurseForge.";
 self.details=[NSButton checkboxWithTitle:@"Details Damage Meter verwalten – verfügbar 20260707.15250.172 TBC" target:self action:@selector(changed:)]; self.details.accessibilityHelp=@"Installiert und aktualisiert Details Damage Meter für Burning Crusade Anniversary über CurseForge.";
 self.pawn=[NSButton checkboxWithTitle:@"Pawn Ausrüstungsvergleich verwalten – verfügbar 2.13.15" target:self action:@selector(changed:)]; self.pawn.accessibilityHelp=@"Installiert und aktualisiert Pawn für Burning Crusade Anniversary über GitHub. Standardmäßig abgewählt.";
 self.dbm=[NSButton checkboxWithTitle:@"Deadly Boss Mods verwalten – verfügbar 12.1.8" target:self action:@selector(changed:)]; self.dbm.accessibilityHelp=@"Installiert und aktualisiert DBM mit den Schlachtzugs- und Dungeon-Modulen für Burning Crusade Anniversary über GitHub.";
 self.gtfo=[NSButton checkboxWithTitle:@"GTFO Gefahrenwarnung verwalten – verfügbar 6.9.1" target:self action:@selector(changed:)]; self.gtfo.accessibilityHelp=@"Installiert und aktualisiert GTFO, die akustische Warnung vor Bodeneffekten, über CurseForge.";
 self.bugsack=[NSButton checkboxWithTitle:@"BugSack und BugGrabber verwalten – verfügbar 12.0.13" target:self action:@selector(changed:)]; self.bugsack.accessibilityHelp=@"Installiert und aktualisiert die Fehlererfassung BugSack samt BugGrabber über GitHub und CurseForge.";
 self.update=[self button:@"Sku und ausgewählte AddOns installieren oder aktualisieren" action:@selector(updateSku:)]; self.update.keyEquivalent=@"\r";
 self.repair=[self button:@"Installation vollständig reparieren" action:@selector(repairSku:)]; self.cancel=[self button:@"Aktualisierung abbrechen" action:@selector(cancelTask:)]; self.cancel.hidden=YES;
 self.inventory=[self button:@"Installierte AddOns anzeigen" action:@selector(showInventory:)]; self.inventory.accessibilityHelp=@"Erstellt eine alphabetisch sortierte, rein lesende Übersicht aller erkannten AddOn-Pakete, Versionen und Quellen.";
 NSButton*browse=[self button:@"AddOns-Ordner manuell auswählen" action:@selector(browse:)],*logs=[self button:@"Diagnosepaket erstellen" action:@selector(logs:)],*check=[self button:@"Installer-Aktualisierung prüfen" action:@selector(checkApp:)],*quit=[self button:@"Beenden" action:@selector(quit:)];
 self.progress=[NSProgressIndicator new]; self.progress.style=NSProgressIndicatorStyleBar; self.progress.indeterminate=YES; self.progress.hidden=YES; self.progress.accessibilityLabel=@"Fortschritt";
 self.output=[NSTextField new]; self.output.editable=NO; self.output.selectable=YES; self.output.bezeled=YES; self.output.drawsBackground=YES; self.output.font=[NSFont monospacedSystemFontOfSize:11 weight:NSFontWeightRegular]; self.output.stringValue=@"Bereit."; self.output.accessibilityLabel=@"Installationsdetails";
 NSStackView*a=[NSStackView stackViewWithViews:@[self.update,self.repair,self.cancel]]; a.orientation=NSUserInterfaceLayoutOrientationHorizontal; a.spacing=8;
 NSStackView*t=[NSStackView stackViewWithViews:@[self.inventory,browse,logs,check,quit]]; t.orientation=NSUserInterfaceLayoutOrientationHorizontal; t.spacing=8;
 NSStackView*managed=[NSStackView stackViewWithViews:@[self.questie,self.atlas,self.details,self.dbm,self.gtfo,self.bugsack,self.pawn]]; managed.orientation=NSUserInterfaceLayoutOrientationVertical; managed.alignment=NSLayoutAttributeLeading; managed.spacing=5;
 NSStackView*s=[NSStackView stackViewWithViews:@[heading,self.status,[self label:@"WoW-Version" size:13 bold:YES],self.games,self.path,[self label:@"Sprachpaket" size:13 bold:YES],self.languages,self.login,[self label:@"Verwaltete Anniversary-AddOns" size:13 bold:YES],managed,a,self.progress,[self label:@"Details" size:13 bold:YES],self.output,t]]; s.orientation=NSUserInterfaceLayoutOrientationVertical; s.alignment=NSLayoutAttributeLeading; s.spacing=9; s.edgeInsets=NSEdgeInsetsMake(20,24,20,24); s.translatesAutoresizingMaskIntoConstraints=NO; [self.window.contentView addSubview:s];
 [NSLayoutConstraint activateConstraints:@[[s.leadingAnchor constraintEqualToAnchor:self.window.contentView.leadingAnchor],[s.trailingAnchor constraintEqualToAnchor:self.window.contentView.trailingAnchor],[s.topAnchor constraintEqualToAnchor:self.window.contentView.topAnchor],[s.bottomAnchor constraintEqualToAnchor:self.window.contentView.bottomAnchor],[self.status.widthAnchor constraintEqualToAnchor:s.widthAnchor constant:-48],[self.games.widthAnchor constraintEqualToAnchor:s.widthAnchor constant:-48],[self.path.widthAnchor constraintEqualToAnchor:s.widthAnchor constant:-48],[self.progress.widthAnchor constraintEqualToAnchor:s.widthAnchor constant:-48],[self.output.widthAnchor constraintEqualToAnchor:s.widthAnchor constant:-48],[self.output.heightAnchor constraintGreaterThanOrEqualToConstant:105]]];
}
- (NSArray*)detected { NSString*h=NSHomeDirectory(); NSArray*r=@[@"/Applications/World of Warcraft",[h stringByAppendingPathComponent:@"Applications/World of Warcraft"]],*f=@[@"_anniversary_",@"_classic_era_",@"_classic_",@"_retail_"]; NSMutableArray*x=[NSMutableArray array]; for(NSString*root in r)for(NSString*fl in f){NSString*p=[root stringByAppendingPathComponent:[NSString stringWithFormat:@"%@/Interface/AddOns",fl]]; BOOL d=NO;if([[NSFileManager defaultManager]fileExistsAtPath:p isDirectory:&d]&&d)[x addObject:p];}return x; }
- (NSString*)flavor:(NSString*)p { if([p containsString:@"/_anniversary_/"])return @"Anniversary";if([p containsString:@"/_classic_era_/"])return @"Classic Era";if([p containsString:@"/_classic_/"])return @"Classic";if([p containsString:@"/_retail_/"])return @"Retail";return @"Manueller AddOns-Ordner"; }
- (NSString*)selected { NSInteger i=self.games.indexOfSelectedItem; return i>=0&&i<(NSInteger)self.paths.count?self.paths[i]:nil; }
- (void)reload:(NSString*)selected { [self.games removeAllItems];for(NSString*p in self.paths){BOOL sku=[[NSFileManager defaultManager]fileExistsAtPath:[p stringByAppendingPathComponent:@"Sku"]];[self.games addItemWithTitle:[NSString stringWithFormat:@"%@%@",[self flavor:p],sku?@" – Sku installiert":@""]];}NSUInteger i=[self.paths indexOfObject:selected];if(i!=NSNotFound)[self.games selectItemAtIndex:i];else if(self.paths.count)[self.games selectItemAtIndex:0];[self updatePath]; }
- (NSControlStateValue)managedState:(NSString*)key { NSString*v=[self.prefs stringForKey:key];if(!v.length)return [key isEqualToString:@"ManagePawn"]?NSControlStateValueOff:NSControlStateValueOn;return[v isEqualToString:@"Nein"]?NSControlStateValueOff:NSControlStateValueOn; }
- (void)loadConfiguration { [self.paths addObjectsFromArray:self.detected];NSString*p=[self.prefs stringForKey:@"SelectedAddonsFolder"]?:@"";if(p.length&&![self.paths containsObject:p])[self.paths addObject:p];[self reload:p];[self.languages selectItemWithTitle:[self.prefs stringForKey:@"LanguagePack"]?:@"Deutsch"];self.login.state=[[self.prefs stringForKey:@"LoginTool"]isEqualToString:@"Ja"]?NSControlStateValueOn:NSControlStateValueOff;self.questie.state=[self managedState:@"ManageQuestie"];self.atlas.state=[self managedState:@"ManageAtlasLoot"];self.details.state=[self managedState:@"ManageDetails"];self.pawn.state=[self managedState:@"ManagePawn"];self.dbm.state=[self managedState:@"ManageDBM"];self.gtfo.state=[self managedState:@"ManageGTFO"];self.bugsack.state=[self managedState:@"ManageBugSack"];[self updateManagedAvailability];[self save]; }
- (void)saveManaged:(NSButton*)button key:(NSString*)key { [self.prefs setObject:button.state==NSControlStateValueOn?@"Ja":@"Nein" forKey:key]; }
- (void)save { if(self.selected)[self.prefs setObject:self.selected forKey:@"SelectedAddonsFolder"];[self.prefs setObject:self.languages.titleOfSelectedItem?:@"Deutsch" forKey:@"LanguagePack"];[self.prefs setObject:self.login.state==NSControlStateValueOn?@"Ja":@"Nein" forKey:@"LoginTool"];[self saveManaged:self.questie key:@"ManageQuestie"];[self saveManaged:self.atlas key:@"ManageAtlasLoot"];[self saveManaged:self.details key:@"ManageDetails"];[self saveManaged:self.pawn key:@"ManagePawn"];[self saveManaged:self.dbm key:@"ManageDBM"];[self saveManaged:self.gtfo key:@"ManageGTFO"];[self saveManaged:self.bugsack key:@"ManageBugSack"];[self.prefs synchronize]; }
- (void)updateManagedAvailability { BOOL anniversary=[self.selected containsString:@"/_anniversary_/"];for(NSButton*b in @[self.questie,self.atlas,self.details,self.dbm,self.gtfo,self.bugsack,self.pawn]){b.enabled=anniversary;b.accessibilityEnabled=anniversary;}NSString*help=anniversary?@"Die ausgewählten AddOns werden zusammen mit Sku aktualisiert.":@"Die zusätzliche AddOn-Verwaltung ist in dieser Ausbaustufe nur für Anniversary verfügbar.";for(NSButton*b in @[self.questie,self.atlas,self.details,self.dbm,self.gtfo,self.bugsack,self.pawn])b.accessibilityHelp=help; }
- (void)updatePath { self.path.stringValue=self.selected?:@"Noch kein AddOns-Ordner ausgewählt.";self.path.accessibilityLabel=self.path.stringValue;[self updateManagedAvailability]; }
- (NSString*)installed { NSString*t=[self.selected stringByAppendingPathComponent:@"Sku/Sku.toc"];NSString*x=t?[NSString stringWithContentsOfFile:t encoding:NSUTF8StringEncoding error:nil]:nil;NSRegularExpression*r=[NSRegularExpression regularExpressionWithPattern:@"(?im)^##\\s*Version:\\s*([^\\r\\n]+)" options:0 error:nil];NSTextCheckingResult*m=[r firstMatchInString:x?:@"" options:0 range:NSMakeRange(0,x.length)];return m?[[x substringWithRange:[m rangeAtIndex:1]]stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet]:nil; }
- (NSDictionary*)addonManifest { NSString*p=[self.selected stringByAppendingPathComponent:@"SkuInstall.json"];NSData*d=p?[NSData dataWithContentsOfFile:p]:nil;if(!d)return @{};NSDictionary*j=[NSJSONSerialization JSONObjectWithData:d options:0 error:nil];NSDictionary*a=[j isKindOfClass:NSDictionary.class]?j[@"addons"]:nil;return[a isKindOfClass:NSDictionary.class]?a:@{}; }
- (BOOL)managedAddonCurrent:(NSDictionary*)manifest key:(NSString*)key version:(NSString*)version roots:(NSArray*)roots { if(![manifest[key] isEqualToString:version])return NO;for(NSString*r in roots)if(![[NSFileManager defaultManager]fileExistsAtPath:[self.selected stringByAppendingPathComponent:r]])return NO;return YES; }
- (NSString*)latestFor:(NSString*)key fallback:(NSString*)fallback { id entry=self.latestCurated[key];id value=[entry isKindOfClass:NSDictionary.class]?entry[@"latest"]:nil;return[value isKindOfClass:NSString.class]&&[value length]?value:fallback; }
- (void)applyLatestCuratedLabels { self.questie.title=[NSString stringWithFormat:@"Questie verwalten – verfügbar %@",[self latestFor:@"Questie" fallback:@"11.37.1"]];self.atlas.title=[NSString stringWithFormat:@"AtlasLootClassic Anniversary verwalten – verfügbar %@",[self latestFor:@"AtlasLoot" fallback:@"2.5.6.12334"]];self.details.title=[NSString stringWithFormat:@"Details Damage Meter verwalten – verfügbar %@",[self latestFor:@"Details" fallback:@"20260707.15250.172 TBC"]];self.dbm.title=[NSString stringWithFormat:@"Deadly Boss Mods verwalten – verfügbar %@",[self latestFor:@"DBM" fallback:@"12.1.8"]];self.gtfo.title=[NSString stringWithFormat:@"GTFO Gefahrenwarnung verwalten – verfügbar %@",[self latestFor:@"GTFO" fallback:@"6.9.1"]];self.bugsack.title=[NSString stringWithFormat:@"BugSack und BugGrabber verwalten – verfügbar %@",[self latestFor:@"BugSack" fallback:@"12.0.13"]];self.pawn.title=[NSString stringWithFormat:@"Pawn Ausrüstungsvergleich verwalten – verfügbar %@",[self latestFor:@"Pawn" fallback:@"2.13.15"]]; }
- (NSArray*)curatedUpdates { if(![self.selected containsString:@"/_anniversary_/"])return @[];NSDictionary*m=self.addonManifest;NSMutableArray*u=[NSMutableArray array];if(self.questie.state==NSControlStateValueOn&&![self managedAddonCurrent:m key:@"CurseQuestie" version:[self latestFor:@"Questie" fallback:@"11.37.1"] roots:@[@"Questie"]])[u addObject:@"Questie"];if(self.atlas.state==NSControlStateValueOn&&![self managedAddonCurrent:m key:@"CurseAtlasLootAnniversary" version:[self latestFor:@"AtlasLoot" fallback:@"2.5.6.12334"] roots:@[@"AtlasLootClassic",@"AtlasLootClassic_Data"]])[u addObject:@"AtlasLootClassic Anniversary"];if(self.details.state==NSControlStateValueOn&&![self managedAddonCurrent:m key:@"CurseDetailsTBC" version:[self latestFor:@"Details" fallback:@"20260707.15250.172_TBC"] roots:@[@"Details",@"Details_DataStorage"]])[u addObject:@"Details Damage Meter"];if(self.pawn.state==NSControlStateValueOn&&![self managedAddonCurrent:m key:@"CursePawnTBC" version:[self latestFor:@"Pawn" fallback:@"2.13.15"] roots:@[@"Pawn"]])[u addObject:@"Pawn"];if(self.dbm.state==NSControlStateValueOn&&![self managedAddonCurrent:m key:@"DBMCore" version:[self latestFor:@"DBM" fallback:@"12.1.8"] roots:@[@"DBM-Core",@"DBM-Raids-BC",@"DBM-Party-BC"]])[u addObject:@"Deadly Boss Mods"];if(self.gtfo.state==NSControlStateValueOn&&![self managedAddonCurrent:m key:@"CurseGTFO" version:[self latestFor:@"GTFO" fallback:@"6.9.1"] roots:@[@"GTFO"]])[u addObject:@"GTFO"];if(self.bugsack.state==NSControlStateValueOn&&(![self managedAddonCurrent:m key:@"BugSack" version:[self latestFor:@"BugSack" fallback:@"12.0.13"] roots:@[@"BugSack"]]||![self managedAddonCurrent:m key:@"CurseBugGrabber" version:@"12.0.21" roots:@[@"!BugGrabber"]]))[u addObject:@"BugSack und BugGrabber"];return u; }
- (NSString*)updateSummaryWithLatestSku:(NSString*)latest { NSMutableArray*u=[NSMutableArray array];NSString*have=self.installed;if(!have||![have isEqualToString:latest])[u addObject:@"Sku"];[u addObjectsFromArray:self.curatedUpdates];if(!u.count)return @"Alle AddOns sind auf dem neuesten Stand.";NSString*names=u.count==1?u.firstObject:[[u subarrayWithRange:NSMakeRange(0,u.count-1)]componentsJoinedByString:@", "];if(u.count>1)names=[NSString stringWithFormat:@"%@ und %@",names,u.lastObject];return u.count==1?[NSString stringWithFormat:@"Für %@ ist ein Update verfügbar.",names]:[NSString stringWithFormat:@"Für %@ sind Updates verfügbar.",names]; }
- (NSString*)spoken:(NSString*)v{return[v stringByReplacingOccurrencesOfString:@"." withString:@" Punkt "];}
- (void)setStatus:(NSString*)s announce:(BOOL)a { self.status.stringValue=s;self.status.accessibilityLabel=s;if(a)NSAccessibilityPostNotificationWithUserInfo(self.status,NSAccessibilityAnnouncementRequestedNotification,@{NSAccessibilityAnnouncementKey:s,NSAccessibilityPriorityKey:@(NSAccessibilityPriorityHigh)}); }
- (void)refreshCuratedWithLatestSku:(NSString*)latest announce:(BOOL)announce { NSTask*t=[NSTask new];t.executableURL=[NSURL fileURLWithPath:@"/bin/bash"];t.arguments=@[[NSBundle.mainBundle.resourcePath stringByAppendingPathComponent:@"SkuInstaller.command"],@"--addon-update-status"];NSPipe*p=[NSPipe pipe];t.standardOutput=p;t.standardError=[NSFileHandle fileHandleWithNullDevice];t.terminationHandler=^(NSTask*finished){NSData*d=[p.fileHandleForReading readDataToEndOfFile];NSDictionary*j=d?[NSJSONSerialization JSONObjectWithData:d options:0 error:nil]:nil;dispatch_async(dispatch_get_main_queue(),^{if([j isKindOfClass:NSDictionary.class])self.latestCurated=j;[self applyLatestCuratedLabels];[self setStatus:[self updateSummaryWithLatestSku:latest] announce:announce];[self reload:self.selected];});};if(![t launchAndReturnError:nil]){[self setStatus:[self updateSummaryWithLatestSku:latest] announce:announce];} }
/* Version detection resolves the releases/latest redirect and reads the tag —
   the same mechanism the Windows installer uses (GitHubClient.cs). Never scrape
   the website HTML for a version string. */
- (void)refreshStatus:(BOOL)announce { [self setStatus:@"Der Aktualisierungsstatus aller ausgewählten AddOns wird geprüft." announce:NO];NSMutableURLRequest*q=[NSMutableURLRequest requestWithURL:[NSURL URLWithString:@"https://github.com/Sku75/Sku-WoW-Addon-TBC/releases/latest"]];q.HTTPMethod=@"HEAD";[[[NSURLSession sharedSession]dataTaskWithRequest:q completionHandler:^(NSData*d,NSURLResponse*r,NSError*e){NSString*tag=r.URL.lastPathComponent?:@"";if([tag hasPrefix:@"v"])tag=[tag substringFromIndex:1];NSRegularExpression*rx=[NSRegularExpression regularExpressionWithPattern:@"^[0-9]+(\\.[0-9]+)+$" options:0 error:nil];NSString*l=[rx firstMatchInString:tag options:0 range:NSMakeRange(0,tag.length)]?tag:@"43.3";dispatch_async(dispatch_get_main_queue(),^{[self refreshCuratedWithLatestSku:l announce:announce];});}]resume]; }
- (void)gameChanged:(id)x{[self updatePath];[self save];[self refreshStatus:YES];}- (void)changed:(id)x{[self save];[self refreshStatus:YES];}
- (NSString*)normalize:(NSString*)p { p=p.stringByStandardizingPath;if([p.lastPathComponent isEqualToString:@"AddOns"]&&[p.stringByDeletingLastPathComponent.lastPathComponent isEqualToString:@"Interface"])return p;if([p.lastPathComponent isEqualToString:@"Interface"])return[p stringByAppendingPathComponent:@"AddOns"];NSString*c=[p stringByAppendingPathComponent:@"Interface/AddOns"];return[[NSFileManager defaultManager]fileExistsAtPath:c]?c:nil; }
- (void)browse:(id)x { NSOpenPanel*p=NSOpenPanel.openPanel;p.title=@"AddOns-Ordner auswählen";p.message=@"Wähle den WoW-Versionsordner oder Interface/AddOns.";p.prompt=@"Auswählen";p.canChooseDirectories=YES;p.canChooseFiles=NO;if([p runModal]!=NSModalResponseOK)return;NSString*q=[self normalize:p.URL.path];if(!q){[self alert:@"Ungültiger Ordner" info:@"Bitte wähle einen WoW-Versionsordner oder Interface/AddOns."];return;}NSError*e;[[NSFileManager defaultManager]createDirectoryAtPath:q withIntermediateDirectories:YES attributes:nil error:&e];if(e){[self alert:@"Ordner nicht verwendbar" info:e.localizedDescription];return;}if(![self.paths containsObject:q])[self.paths addObject:q];[self reload:q];[self save];[self refreshStatus:YES]; }
- (void)busy:(BOOL)b { self.update.enabled=!b;self.repair.enabled=!b;self.inventory.enabled=!b;self.games.enabled=!b;self.languages.enabled=!b;self.login.enabled=!b;self.cancel.hidden=!b;self.progress.hidden=!b;if(b){for(NSButton*m in @[self.questie,self.atlas,self.details,self.dbm,self.gtfo,self.bugsack,self.pawn])m.enabled=NO;}else [self updateManagedAvailability];b?[self.progress startAnimation:nil]:[self.progress stopAnimation:nil]; }
- (void)backend:(NSString*)arg done:(void(^)(int,NSString*))done {
 [self save]; [self busy:YES]; self.output.stringValue=@"Vorgang wird gestartet …\n";
 self.task=[NSTask new]; self.task.executableURL=[NSURL fileURLWithPath:@"/bin/bash"];
 self.task.arguments=@[[NSBundle.mainBundle.resourcePath stringByAppendingPathComponent:@"SkuInstaller.command"],arg];
 self.pipe=[NSPipe pipe]; self.task.standardOutput=self.pipe; self.task.standardError=self.pipe;
 NSMutableData*all=[NSMutableData data]; __weak typeof(self) weakSelf=self;
 self.pipe.fileHandleForReading.readabilityHandler=^(NSFileHandle*h){
  NSData*d=h.availableData; if(!d.length)return; @synchronized(all){[all appendData:d];}
  NSString*s=[[NSString alloc]initWithData:d encoding:NSUTF8StringEncoding];
  dispatch_async(dispatch_get_main_queue(),^{typeof(self) self=weakSelf;if(self&&s.length)self.output.stringValue=[self.output.stringValue stringByAppendingString:s];});
 };
 self.task.terminationHandler=^(NSTask*t){
  typeof(self) self=weakSelf;if(!self)return; self.pipe.fileHandleForReading.readabilityHandler=nil;
  NSString*s; @synchronized(all){s=[[NSString alloc]initWithData:all encoding:NSUTF8StringEncoding]?:@"";}
  dispatch_async(dispatch_get_main_queue(),^{typeof(self) self=weakSelf;if(!self)return;[self busy:NO];self.task=nil;done(t.terminationStatus,s);});
 };
 NSError*e;if(![self.task launchAndReturnError:&e]){[self busy:NO];self.task=nil;[self alert:@"Vorgang konnte nicht gestartet werden" info:e.localizedDescription];}
}
- (void)install:(BOOL)repair { if(!self.selected){[self browse:nil];if(!self.selected)return;}[self setStatus:repair?@"Vollständige Reparatur läuft. Bitte warten.":@"Sku und ausgewählte AddOns werden aktualisiert. Bitte warten." announce:YES];[self backend:repair?@"--headless-update-force":@"--headless-update" done:^(int c,NSString*s){[self alert:c==0?@"Aktualisierung abgeschlossen":@"Aktualisierung fehlgeschlagen" info:c==0?(repair?@"Sku und alle ausgewählten AddOns wurden vollständig neu installiert.":@"Sku und die ausgewählten Anniversary-AddOns wurden erfolgreich installiert oder aktualisiert."):@"Die vorherigen Versionen wurden bei einem Austauschfehler wiederhergestellt. Erstelle bei Bedarf ein Diagnosepaket."];[self refreshStatus:YES];}]; }
- (void)updateSku:(id)x{[self install:NO];}- (void)repairSku:(id)x{[self install:YES];}- (void)cancelTask:(id)x{if(self.task.running){[self.task interrupt];[self setStatus:@"Aktualisierung wird abgebrochen." announce:YES];}}
- (void)showInventory:(id)x{if(!self.selected){[self browse:nil];if(!self.selected)return;}[self setStatus:@"Die installierten AddOns werden erfasst." announce:YES];[self backend:@"--addon-inventory" done:^(int c,NSString*s){NSString*result=[s stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet];self.output.stringValue=result.length?result:@"Es wurden keine AddOns erkannt.";self.output.accessibilityLabel=@"Installierte AddOns";[self setStatus:c==0?@"Die AddOn-Liste wurde erstellt.":@"Die AddOn-Liste konnte nicht erstellt werden." announce:YES];}];}
- (void)logs:(id)x{[self backend:@"--collect-logs" done:^(int c,NSString*s){[self alert:c==0?@"Diagnosepaket erstellt":@"Diagnose fehlgeschlagen" info:c==0?[NSString stringWithFormat:@"Die ZIP-Datei liegt hier:\n%@",[s stringByTrimmingCharactersInSet:NSCharacterSet.whitespaceAndNewlineCharacterSet]]:@"Das Paket konnte nicht erstellt werden."];}];}
- (void)checkApp:(id)x{[self backend:@"--self-update-check" done:^(int c,NSString*s){if(c!=0){[self alert:@"Prüfung fehlgeschlagen" info:@"Die Installer-Version konnte momentan nicht geprüft werden."];return;}if([s containsString:@"AVAILABLE=1"]){NSRegularExpression*r=[NSRegularExpression regularExpressionWithPattern:@"LATEST=([^\\r\\n]+)" options:0 error:nil];NSTextCheckingResult*m=[r firstMatchInString:s options:0 range:NSMakeRange(0,s.length)];NSString*v=m?[s substringWithRange:[m rangeAtIndex:1]]:@"neu";NSAlert*a=[NSAlert new];a.messageText=@"Neue Installer-Version verfügbar";a.informativeText=[NSString stringWithFormat:@"Version %@ kann aus dem offiziellen Repository geladen, per SHA-256 und Developer-ID-Signatur geprüft und installiert werden.",v];[a addButtonWithTitle:@"Jetzt aktualisieren"];[a addButtonWithTitle:@"Später"];if([a runModal]==NSAlertFirstButtonReturn){[self backend:@"--self-update" done:^(int code,NSString*out){if(code==0)[NSApp terminate:nil];else[self alert:@"Installer-Aktualisierung fehlgeschlagen" info:@"Das vorhandene Programm wurde nicht ersetzt. Das heruntergeladene Paket war nicht verfügbar oder bestand die Sicherheitsprüfung nicht."];}];}}else[self alert:@"Installer ist aktuell" info:@"Es ist keine neuere veröffentlichte macOS-Version verfügbar."];}];}
- (void)checkInstallerAutomatically { NSTask*t=[NSTask new];t.executableURL=[NSURL fileURLWithPath:@"/bin/bash"];t.arguments=@[[NSBundle.mainBundle.resourcePath stringByAppendingPathComponent:@"SkuInstaller.command"],@"--self-update-check"];NSPipe*p=[NSPipe pipe];t.standardOutput=p;t.standardError=[NSFileHandle fileHandleWithNullDevice];t.terminationHandler=^(NSTask*finished){NSData*d=[p.fileHandleForReading readDataToEndOfFile];NSString*s=[[NSString alloc]initWithData:d encoding:NSUTF8StringEncoding]?:@"";if([s containsString:@"AVAILABLE=1"])dispatch_async(dispatch_get_main_queue(),^{[self checkApp:nil];});};[t launchAndReturnError:nil]; }
- (void)alert:(NSString*)t info:(NSString*)i{NSAlert*a=[NSAlert new];a.messageText=t;a.informativeText=i;[a addButtonWithTitle:@"Schließen"];[a runModal];}
- (void)quit:(id)x{if(!self.task.running)[NSApp terminate:nil];}- (BOOL)windowShouldClose:(NSWindow*)w{if(self.task.running){[self alert:@"Aktualisierung läuft" info:@"Brich sie zuerst mit dem Schalter Aktualisierung abbrechen ab."];return NO;}return YES;}- (void)windowWillClose:(NSNotification*)n{[NSApp terminate:nil];}
@end
int main(int argc,const char*argv[]){@autoreleasepool{NSApplication*a=NSApplication.sharedApplication;SkuDelegate*d=[SkuDelegate new];a.delegate=d;[a run];}return 0;}
